#!/bin/sh

set -eu

if [ $(id -u) -ne 0 ]; then
	echo "yer gonna need root"
	exit 1
fi
if [ ! -f .secrets ]; then
	echo "yer gonna need the secrets"
	exit 1
fi

apk update
apk add tzdata mosh tmux hitch acme.sh varnish opensmtpd postgresql

grep -q '^hitch:' /etc/group  || addgroup -S hitch
grep -q '^hitch:' /etc/passwd || adduser -h /dev/null -s /sbin/nologin -DHS -G hitch hitch

for s in crond ntpd postgresql hitch varnishd smtpd; do
	rc-update add $s
	rc-service $s start
done

# Copy files.
(cd ./etc && find -type f | while read f; do
	dst="/etc/$f"
	mkdir -p "$(dirname "$dst")"
	sed -f ../.secrets "$f" > "$dst"

	chmod $(stat -c %a "$f") "$dst"
	echo "$dst"
done)
sed -f .secrets 'run-goatletter'  > /home/martin/run-goatletter
sed -f .secrets 'run-goatcounter' > /home/martin/run-goatcounter

# Create certificates.
[ -f /etc/hitch/pem/goatcounter.pem ] || /etc/hitch/create-cert goatcounter.com
[ -f /etc/hitch/pem/goatletter.pem ]  || /etc/hitch/create-cert goatletter.com
# TODO: renew certs; default cronjob won't work for the above two.
#acme.sh --home '/etc/hitch/acme.sh' --install-cronjob

# Setup iptables
# TODO: iptables is too retarded and gave me cancer. Easiest way to get Firewall
# on Linux: run OpenBSD/pf in VM? (only half joking...)
