#!/bin/sh

exec ./goatletter/bin/goatletter \
	-prod \
	-emailerrors  'errors@goatcounter.com' \
	-domain       'goatletter.com' \
	-domainstatic 'static.goatletter.com' \
	-smtp         'smtp://carpetsmoker%40fastmail.nl:$%fm-key%$@smtp.fastmail.com:587' \
	"$@" 2>&1 |
	tee "logs/goatletter.$(date +%Y%m%d)"
