#!/bin/sh
#
# TODO: make it easier to run older versions:
#
#   ./run-goatcounter             run latest
#   ./run-goatcounter 1           run one older
#   ./run-goatcounter 2           run two older
#   ./run-goatcounter 132fabc     run specific commit
#

exec ./goatcounter/bin/goatcounter \
	-prod \
	-plan         'personal' \
	-emailerrors  'errors@goatcounter.com' \
	-domain       'goatcounter.com' \
	-domainstatic 'gc.zgo.at,static.goatcounter.com' \
	-smtp         'smtp://carpetsmoker%40fastmail.nl:$%fm-key%$@smtp.fastmail.com:587' \
	-certdir      '/home/martin' \
	-dbconnect    'user=martin dbname=goatcounter sslmode=disable' -pgsql \
	-stripe       '$%stripe-key%$:$%stripe-wh%$:pk_live_0GXvIndCJpHrEIwPiWxFtqoc00CLyksvMg' \
	"$@" 2>&1 |
	tee "logs/goatcounter.$(date +%Y%m%d)"
