#!/bin/sh

cd /home/goatcounter
exec chpst -u goatcounter:goatcounter /home/goatcounter/bin/goatcounter saas \
	-listen   ':8081' \
	-tls      'none,acme' \
	-db       'postgresql://dbname=goatcounter sslmode=disable' \
	-domain   'goatcounter.com,static.zgo.at,gc.zgo.at' \
	-smtp     'smtp://martin%40arp242.net:$%fm-key%$@smtp.fastmail.com:587' \
	-errors   'mailto:errors@goatcounter.com' \
	-geodb    '/home/goatcounter/GeoLite2-City.mmdb' \
	-stripe   '$%stripe-key%$:$%stripe-wh%$:pk_live_0GXvIndCJpHrEIwPiWxFtqoc00CLyksvMg:$%github-wh%$' \
	-debug    'dashboard,req,cron' \
	-automigrate
