#!/bin/sh
#

su martin -c 'pg_dump goatcounter | bzip2 > "/home/martin/backup/goatcounter.$(date +%Y-%m-%dT%H:%M:%S).sql.bz2"'
su martin -c 'find /home/martin/backup/goatcounter.* -mtime +14 -delete'
