#!/bin/sh
#
# Create certificates. See:
# https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode
#
# --yes-I-know-dns-manual-mode-enough-go-ahead-please 
#   Force to use dns manual mode: https://github.com/Neilpang/acme.sh/wiki/dns-manual-mode
#

set -eu

if [ -z "${1:-}" ]; then
	echo "need domain as first argument"
	exit 1
fi
domain=$1

cd /etc/hitch
mkdir -p pem

# Special-fu for GoatCounter and GoatLetter, as *.example.com wildcard requires
# DNS verification.
if [ "$domain" = "goatcounter.com" ] || [ "$domain" = "goatletter.com" ]; then
	env CF_Email=$%cf-email%$ CF_Key=$%cf-key%$ \
		acme.sh --home '/etc/hitch/acme.sh' \
		--issue --dns dns_cf \
		--domain-alias "${domain%%.*}.goatcount.com" \
		-d "$domain" -d "*.$domain"
else
	echo "unknown domain: '$domain'"
	exit 2
fi
cat "acme.sh/$domain/$domain.key" \
	"acme.sh/$domain/fullchain.cer" \
	> "pem/$domain.pem"

# Ensure permissions are correct.
chmod 700 pem
chmod -R go-rx acme.sh
chown -R hitch:hitch pem
chmod 600 pem/*.pem
