#!/bin/sh
#
# Create certificates. See:
# https://github.com/Neilpang/acme.sh/wiki/DNS-alias-mode
#
# --yes-I-know-dns-manual-mode-enough-go-ahead-please 
#   Force to use dns manual mode: https://github.com/Neilpang/acme.sh/wiki/dns-manual-mode
#

cd /etc/hitch
mkdir -p pem

# GoatCounter
env CF_Email=$%cf-email%$ CF_Key=$%cf-key%$ \
	acme.sh \
	--home '/etc/hitch/acme.sh' \
	--test \
	--issue --dns dns_cf \
	--domain-alias goatcounter.goatcount.com \
	-d goatcounter.com -d '*.goatcounter.com'
cat acme.sh/goatcounter.com/goatcounter.com.key \
    acme.sh/goatcounter.com/fullchain.cer \
    > pem/goatcounter.pem

# GoatLetter
env CF_Email=$%cf-email%$ CF_Key=$%cf-key%$ \
	acme.sh \
	--home '/etc/hitch/acme.sh' \
	--test \
	--issue --dns dns_cf \
	--domain-alias goatletter.goatcount.com \
	-d goatletter.com -d '*.goatletter.com'
cat acme.sh/goatletter.com/goatletter.com.key \
    acme.sh/goatletter.com/fullchain.cer \
    > pem/goatletter.pem


chmod 700 pem
chmod -R go-rx acme.sh
chown -R hitch:hitch pem
# acme.sh --install-cronjob

chmod 600 pem/goatcounter.pem
