#!/bin/sh

set -euC

psql -X -P null=NULL --csv goatcounter \
        < /home/goatcounter/data-screensize.sql |
        gzip > /tmp/screensize.csv.gz.new
mv /tmp/screensize.csv.gz.new /tmp/screensize.csv.gz

psql -X -P null=NULL --csv goatcounter \
        < /home/goatcounter/data-ua.sql |
        gzip > /tmp/ua.csv.gz.new
mv /tmp/ua.csv.gz.new /tmp/ua.csv.gz

psql -X -P null=NULL --csv goatcounter \
        < /home/goatcounter/data-bots.sql |
        gzip > /tmp/bots.csv.gz.new
mv /tmp/bots.csv.gz.new /tmp/bots.csv.gz

exit 0
